### ISSUE TITLE
Obfuscated script contains newline symbols

### ISSUE THREAD

**Issue by CaledoniaProject** [danielbohannon/Invoke-Obfuscation#18]
I'm using the following method to obfuscate a file,

```
powershell -ep bypass Import-Module .\Invoke-Obfuscation.psd1; Out-ObfuscatedStringCommand -Path c:\my.ps1 > c:\out.ps1
```

But the script created contains newline symbols and will not execute. I will have to remove the `\r\n` symbols manually

Any ideas?

**Comment by CaledoniaProject** [comment]
Content of my.ps1

```
[System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms"); [Windows.Forms.MessageBox]::Show("A", "B", [Windows.Forms.MessageBoxButtons]::OK, [Windows.Forms.MessageBoxIcon]::Information)
```

**Comment by danielbohannon** [comment]
So you're saying that there are not newline characters in the input? Because the string obfuscation functions were designed to maintain newline characters existing in the input command or script being obfuscated.

**Comment by CaledoniaProject** [comment]
Never mind, looks like a windows console issue
