### ISSUE TITLE
May fail on non-ENUS windows installations

### ISSUE THREAD

**Issue by ilgrank** [danielbohannon/Invoke-Obfuscation#22]
Hi Daniel,

Thanks for this awesome project!

One of the 'scrambling' option uses char index of $Env:Public to compose 'IEX':
`$InvokeExpressionSyntax += $InvocationOperator + "( `$env:Public[13]+`$env:Public[5]+'x')"`
the problem is, that 
on ENUS $Env:Public resolves to "C:\Users\Public" ->IEX
on ITIT it resolves to "C:\Profili\Public" -> BOX

so the encode commands get an 1inN chance to not be working on non-ENUS windows.

**Comment by danielbohannon** [comment]
Thanks for pointing out this regional value difference. This invocation option has been commented out in a24aca7e8d245c74ce8b52bc2773b3433673b643 for more stable compatibility.
