### ISSUE TITLE
Some of the encoding tecniques prevent variable manipulation

### ISSUE THREAD

**Issue by ilgrank** [danielbohannon/Invoke-Obfuscation#24]
Hi Daniel,

Thanks for this awesome project!

In order to preserve scripts tab-parameters from CLI, I do encode all of the script BUT the param() part
Later In the (encoded) script, I do a 
`remove-variable -Name SomeVar`
Sometimes, (75%,but NOT Always) after encoding (I'm using ASCII), I get a
`Cannot overwrite variable SomeVarbecause the variable has been optimized.`
I have yet to track down what line of code causes this tho

**Comment by danielbohannon** [comment]
Can you provide a small example function that exhibits this behavior so I can try to reproduce on my end?

**Comment by ilgrank** [comment]
Cannot reproduce anymore on 1.8
Thanks! :) 👍
