### ISSUE TITLE
Force Close 

### ISSUE THREAD

**Issue by tiptaptop** [danielbohannon/Invoke-Obfuscation#26]
Hello, 
When I try to init Invoke-Obfuscation my Powershell console force close. I enter this command : 
Import-Module ./Invoke-Obfuscation.ps1 
Invoke-Obfuscation
Then the last command my shell force close. 
Thanks for your help ! 
Windows 10 - Fall Creator Update - Powershell V5.1

**Comment by cobbr** [comment]
You'll want to import the `Invoke-Obfuscation.psd1` file, not the `Invoke-Obfuscation.ps1` file.

I'm not sure what would be causing your shell to close though. Give this a shot and see if it helps:
```
Import-Module ./Invoke-Obfuscation.psd1
Invoke-Obfuscation
```

**Comment by danielbohannon** [comment]
You're correct, @cobbr. There's a check in Invoke-Obfuscation.ps1 that throws a warning and exits if the module is not loaded. I guess I should have included a few seconds of sleep before that exit so you could see the error :) If you run PowerShell from within cmd.exe then you can see the error after it exits, but running the standalone powershell.exe will just exit before you can read the error.

**Comment by tiptaptop** [comment]
Yes, It's work ! 
I try with cmd and yes I see the error output. So, just a little mistake from me. 
Thank you very much for your help !
