### ISSUE TITLE
Is there any way to deobfuscate powershell scripts?

### ISSUE THREAD

**Issue by beraphin** [danielbohannon/Invoke-Obfuscation#27]

**Comment by danielbohannon** [comment]
There is not currently a PowerShell deobfuscation script or function that is publicly available. The best deobfuscator (for most layers of obfuscation) is PowerShell 5.0+'s script block logging (EID 4104). This will remove all layers of obfuscation except for the TOKEN layer obfuscation.

**Comment by danielbohannon** [comment]
For detecting obfuscated PowerShell you might be interested in trying out [Revoke-Obfuscation](https://github.com/danielbohannon/Revoke-Obfuscation).
