### ISSUE TITLE
Feature Request - Changing Function Names

### ISSUE THREAD

**Issue by CG-root** [danielbohannon/Invoke-Obfuscation#38]
Hi,

Is there an option to modify all function names and variables and their references in a PS1 script?

for example, the variable won't get a random prefix but its entire name will be changed.

Thanks !

**Comment by cobbr** [comment]
@CG-root To answer your question, no this is not an option currently.

I agree that it's something that could be valuable, but probably not the intended functionality of Invoke-Obfuscation. @danielbohannon may have other thoughts.
