### ISSUE TITLE
This command exceeds the cmd.exe maximum length of 8190. ?

### ISSUE THREAD

**Issue by Phoenix1112** [danielbohannon/Invoke-Obfuscation#40]
hello daniel .  i am triying for encode with my powershell backdoor. but it is not working ..

What can I do for it

WARNING: This command exceeds the cmd.exe maximum length of 8190.
         Its length is 22848 characters.

![virtualbox_windows 8](https://user-images.githubusercontent.com/42475284/48144862-b26fbc00-e2c2-11e8-9c18-c780fdc67dd0.png)

**Comment by k1epto** [comment]
BUMP

**Comment by danielbohannon** [comment]
This is a warning and not an error. It just means that the command is too long to copy into a cmd.exe command prompt as a one-liner. So if you see this error you can try to run UNDO to keep retrying obfuscation options until you find one that is short enough, or just plan on not executing the entire obfuscation command as a one-liner.

For example, for the ENCODING options in the screenshot in this Github Issue I computed the "bloat factor" in this blog post on using Invoke-Obfuscation: https://www.danielbohannon.com/blog-1/2017/12/2/the-invoke-obfuscation-usage-guide-part-2

Hope this helps!
