### ISSUE TITLE
PowerShell/Pklotide.A Detected in Onedrive

### ISSUE THREAD

**Issue by sjoonas** [danielbohannon/Invoke-Obfuscation#41]
Hi,

Im getting error in Onedrive/AV detecting PowershellPKlotide.A in:
Out-PowerShellLauncher.ps1

Cant find more information where or which part of the script it is detecting.

Is this normal behaviour or have any information which part might get detected as malicious? :)

**Comment by danielbohannon** [comment]
Parts of Invoke-Obfuscation are being detected as malicious script content, which is good because it means the industry is progressing :)

Some users have found that disabling A/V while using Invoke-Obfuscation to be helpful.
