### ISSUE TITLE
Trojan:PowerShell/PSAttackTool.A

### ISSUE THREAD

**Issue by justinainsworth** [danielbohannon/Invoke-Obfuscation#44]
I had used Invoke-Obfuscation in the past.  I downloaded the most recent version yesterday, and when i loaded the module on my test machine, i immediately got a notice that the file was infected with PowerShell/PSAttackTool.A, and PowerShell/Pklotide.A.  This is on Windows Server 2019 with Windows Defender AV.

Hopefully this issue can be resolved.

**Comment by danielbohannon** [comment]
I do not have any control over Windows Defender signatures hitting on this project's source code.
