### ISSUE TITLE
obfuscated output truncated 

### ISSUE THREAD

**Issue by shellchocolat** [danielbohannon/Invoke-Obfuscation#45]
Hello, 

I try to obfuscate a remotely-hosted script, and use the 
'''powershell
SET SCRIPTPATH http://....../myscript.ps1
'''

then i use the TOKEN menu and all seems doing well, but when the obfuscated output is displayed, it seems truncated (obvisously).

My question is how to get the ouptut not truncated and redirected to a specified file?

Best regards

**Comment by danielbohannon** [comment]
The truncation is just for easier display purposes. The full content is present in memory. You can output it to your clipboard with **CLIP** or to a file on disk with **OUT**.
