### ISSUE TITLE
The cmdlet does not start

### ISSUE THREAD

**Issue by hollerith** [danielbohannon/Invoke-Obfuscation#49]
### Issue running Invoke-Obfuscation

1. I instantiate Windows Server 2019 Datacenter from Amazon AWS EC2. 
2. I install git and git clone the repository to the Administrator's Documents folder. 
3. I navigate to the new folder. I issue the commands as per the repository's README.md. 

> Import-Module ./Invoke-Obfuscation.psd1
> Invoke-Obfuscation

4. I get the following warning:

> The term 'Invoke-Obfuscation' is not recognized as the name of a cmdlet, function, script file,
or operable program.

5. I change the documented command to include the local path. `.\`

#### No warning but nothing happens. 

```
PS C:\Users\Administrator\Documents> cd Invoke-Obfuscation
PS C:\Users\Administrator\Documents\Invoke-Obfuscation> Import-Module ./Invoke-Obfuscation.psd1
PS C:\Users\Administrator\Documents\Invoke-Obfuscation> Invoke-Obfuscation
Invoke-Obfuscation : The term 'Invoke-Obfuscation' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Invoke-Obfuscation
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-Obfuscation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command Invoke-Obfuscation was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\Invoke-Obfuscation". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Administrator\Documents\Invoke-Obfuscation> .\Invoke-Obfuscation
PS C:\Users\Administrator\Documents\Invoke-Obfuscation> :(
```

**Comment by cobbr** [comment]
I've seen this affect a couple other people lately. Be sure to disable Windows Defender prior to closing.

**Comment by gearcapitan** [comment]
![imagen](https://user-images.githubusercontent.com/13740942/54477220-734efb80-47cb-11e9-84fb-b6cd48f23d00.png)
i have the same problem

**Comment by cobbr** [comment]
Hey @gearcapitan, seems like the same issue with Windows Defender. Unfortunately, disabling defender through the GUI will not do the trick. Defender constantly re-enables itself. You'll need to disable through the registry, and re-clone.
