### ISSUE TITLE
Exclude function names from token randomization

### ISSUE THREAD

**Issue by IISResetMe** [danielbohannon/Invoke-Obfuscation#7]
PSParser.Tokenize() treats function name literals as CommandArgument tokens. This causes the TOKEN\ARGUMENT\1 (Random Case) routine to quote the function name, incidentally invalidating function definitions.

Suggested way of avoiding this is to exclude CommandArgument tokens in Out-ObfuscatedTokenCommand from random quoting if the preceding token is the function keyword

**Comment by danielbohannon** [comment]
Issue fixed in d419d0b4a0592c0cd48d7a22d462477f4b976970 release.
